apiVersion: v1
kind: Pod
metadata: 
  name: db
  labels:
    app: db
spec:
  containers:
  - name: postgresql-app
    image: postgres
    env:  
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"
      - name: POSTGRES_DB
        value: "postgres"